addSbtPlugin("org.jmotor.sbt" % "sbt-dependency-updates" % "1.2.1")
//addSbtPlugin("org.scala-js" % "sbt-scalajs" % "0.6.29")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "0.6.31")
addSbtPlugin("io.github.cquiroz" % "sbt-tzdb" % "0.3.2")
//addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.0.0-RC2")
