addSbtPlugin("org.jmotor.sbt" % "sbt-dependency-updates" % "1.2.2")
//addSbtPlugin("org.scala-js" % "sbt-scalajs" % "0.6.29")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "0.6.31")
addSbtPlugin("ch.epfl.scala" % "sbt-scalajs-bundler-sjs06" % "0.17.0")
addSbtPlugin("io.github.cquiroz" % "sbt-tzdb" % "0.4.0")
//addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.0.0-RC2")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.3.2")
